apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup3-cronjob
spec:
schedule: "0 0 * * *" #runs at midnight everyday,0  minutes (the job will run at the start of the hour) 0 hours (the job will run at the start of the day). *** denotes any day of the month,any month, any day of the week
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-trial
            image: pes2ug21cs137/finalproject:latest
            imagePullPolicy: IfNotPresent
          restartPolicy: Never  # Ensures the job doesn't automatically restart after completion
  successfulJobsHistoryLimit: 1  # Keep only the most recent successful job
  failedJobsHistoryLimit: 1  # Keep only the most recent failed job
